expiry:
  prefix: "expiry "
  format: "yyyy-MM-dd"

longevity:
  defaultExpiry: 3
  foodExpiryMap:
    BEETROOT_SOUP: 6
    MUSHROOW_STEW: 6
    RABBIT_STEW: 10
    BREAD: 6
    # below never expire
    GOLDEN_APPLE: null
    ENCHANTED_GOLDEN_APPLE: null

sickness:
  chanceOfGettingSick: 0.25
  effectDuration:
    max: 30
    min: 10
  hungerDuration:
    max: 120
    min: 40
  possibleEffects:
    POISON
    CONFUSION
    BLINDNESS

debug:
  alwaysTriggerExpiry: false

