expiry:
  format:
    prefix: "expiry "
    format: "yyyy-MM-dd"
    alwaysMakeExpired: false

  longevity:
    defaultExpiry: 3
    foodExpiryMap:
      BEETROOT_SOUP: 6
      MUSHROOM_STEW: 6
      RABBIT_STEW: 10
      BREAD: 6
      # below never expire
      GOLDEN_APPLE: -1
      ENCHANTED_GOLDEN_APPLE: -1

  alwaysTrigger: false

  startDate:
    day: 1
    month: 1
    year: 2019


sickness:
  chanceOfGettingSick: 0.8
  effectDuration:
    max: 30
    min: 10
  hungerDuration:
    max: 120
    min: 40
  possibleEffects: [POISON,CONFUSION,BLINDNESS]
  alwaysTrigger: false

showFoodTypeWhenEaten: false
